[package]
name = "shucked-lsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Language server protocol implementation for shucked"

[features]
fuzzing = []

[dependencies]
anyhow = { workspace = true }
crossbeam = { workspace = true }
globset = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true }
notify = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
shucked-ast = { workspace = true }
shucked-command = { workspace = true }
shucked-config = { workspace = true }
shucked-discover = { workspace = true }
shucked-formatter = { workspace = true }
shucked-indexer = { workspace = true }
shucked-linter = { workspace = true }
shucked-parser = { workspace = true }
shucked-semantic = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
